### ISSUE TITLE
Category view doesn't handle Orientation Switch well.

### ISSUE THREAD

**Issue by davidzech** [ucsdCSE110wi16/CSE110W240T3#2]

**Comment by ChaoticTempest** [comment]
hmm. I'll have to go into the Parse backend and have to deal with that. The positioning of image and text is off since the layouts parameters aren't well defined. A fix will be on the way

**Comment by ChaoticTempest** [comment]
Oh and I see what you mean. After changing orientation, it has this weird side affect in the background. Will have to look further into that.

**Comment by ChaoticTempest** [comment]
I believe I fixed the issue with changing orientation. In instantiating and adding the fragment to rootActivity, the code for it had two fm.beginTransactions() which might have caused some overlaying of fragments in the background. It should be fixed with the previous commits with category ui and confirm me on this if isn't.

**Comment by davidzech** [comment]
There's still an issue with this. The Activity isn't rebuilding the fragment stack properly. Should be an easy fix though
